import { StrictMode } from "react";
import ReactDOM from "react-dom";

import App from "./App";

const rootElement = document.getElementById("root");
ReactDOM.render(
  <StrictMode>
    <App />
  </StrictMode>,
  rootElement
);

/* Current Year is Generated by React JS*/

const currentDate = new Date();
const today_date = currentDate.getDate();
const current_year = new Date().getFullYear();

ReactDOM.render(
  <div>
    <h1>Current Year is Generated by React JS</h1>
    <h3>Current Year is : {current_year}</h3>
    <h4>Current Date is : {today_date}</h4>
  </div>,
  document.getElementById("container")
);
